# Post a job
POST http://localhost:3000/consumer/job
Content-Type: application/json

{
    "userId" : 1,
    "clothingId" : 1,
    "description": "Id cupidatat dolore id magna consequat dolore elit voluptate culpa.",
    "statusId" : 1,
    "budget" : null,
    "images" : [
        "imagebytes1",
        "imagebytes2",
        "imagebytes3"
    ]
}

###

# Get all jobs
GET http://localhost:3000/maker/jobs

###

# send quotes
POST http://localhost:3000/maker/send-quotes
Content-Type: application/json

{
    "makerId" : 1,
    "jobId" : 1,
    "price" : 450.50,
    "comments" : "Quis deserunt minim incididunt sunt consequat nulla deserunt cupidatat."
}

###

# Register user
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "firstname" : "Gardyan",
    "lastname" : "Akbar",
    "phone" : "1234567890",
    "email" : "gardyanakbar99@gmail.com",
    "address" : "60 Northfields Ave, Keiraville",
    "postal" : 2500,
    "state" : "NSW",
    "password" : "password123"
}

###
# Login user
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email" : "gardyanakbar99@gmail.com",
    "password" : "password123"
}

###

# get all clothing types
GET http://localhost:3000/queries/clothings

###

# get user
GET http://localhost:3000/queries/user/1

###

# get all status types
GET http://localhost:3000/queries/statuses