# Post a job
POST http://localhost:3000/consumer/job
Content-Type: application/json

{
    "userId" : 1
}

###

# Register user
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "firstname" : "Gardyan",
    "lastname" : "Akbar",
    "phone" : "1234567890",
    "email" : "gardyanakbar99@gmail.com",
    "address" : "60 Northfields Ave, Keiraville",
    "postal" : 2500,
    "state" : "NSW",
    "password" : "password123"
}

###
# Login user
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email" : "gardyanakbar99@gmail.com",
    "password" : "password123"
}
